# Generated by Django 5.2.6 on 2025-10-22 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_tag_message_delete_comment_delete_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReplyRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message",
                        to="main.message",
                    ),
                ),
                (
                    "reply_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reply_message",
                        to="main.message",
                    ),
                ),
            ],
        ),
    ]
