# Generated by Django 5.2.6 on 2025-10-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_replyrelation"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="reply_messages",
            field=models.ManyToManyField(blank=True, to="main.message"),
        ),
        migrations.DeleteModel(
            name="ReplyRelation",
        ),
    ]
