# Generated by Django 5.2.6 on 2025-10-22 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_message_reply_messages_delete_replyrelation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="reply_messages",
            new_name="reply_to",
        ),
    ]
