# Generated by Django 5.2.6 on 2025-11-28 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_rename_reply_messages_message_reply_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="reply_to",
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "child_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reply_from_child_message",
                        to="main.message",
                    ),
                ),
                (
                    "parent_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reply_from_parent_message",
                        to="main.message",
                    ),
                ),
            ],
        ),
    ]
